version: '2'

services:
  logstash:
    build: ./
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./pipeline/:/usr/share/logstash/pipeline
      - /etc/hosts:/etc/hosts
      - /etc/resolv.conf:/etc/resolv.conf
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

networks:
  elk:
    driver: bridge