version: '2'

services:
  logstash:
    build: .
    volumes:
      - ./config/:/etc/logstash/conf.d/
      - ./conf.d/:/etc/logstash/conf.d/
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

networks:
  elk:
    driver: bridge
